services:
  pipelines:
    build: 
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - POETRY_VIRTUALENVS_PATH=/app/${ENVS_PATH}/${VENV_NAME}
      - POETRY_VIRTUALENVS_CREATE=true
      - POETRY_VIRTUALENVS_IN_PROJECT=false
    env_file:
      - .env
    volumes:
      - pipelines:/app/pipelines
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
      - venv:/app/${ENVS_PATH}/${VENV_NAME}

    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

    healthcheck:
      test: ["CMD", "curl", "-f", "http://pipelines:${PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      bash -c "
        echo 'PATH: $PATH' && \

        echo 'Installing dependencies...' && \
        poetry env use python3.12 && \
        poetry install --no-interaction -vv --no-root;
        echo 'Current environment variables:' && \
        printenv && \
        echo 'Starting pipelines...' && \
        poetry run uvicorn main:app --host "$HOST" --port "$PORT" --forwarded-allow-ips '*' --reload 
      "

volumes:
  pipelines:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: './pipelines'



  venv:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: './${ENVS_PATH}'